Repository apache/openwhisk-devtools, pull requests merged in 2019-04, with the labels that each got.

#234 PlatformFactory with Knative and OW impls
  .gitignore
  README.md
  knative-build/runtimes/javascript/app.js
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/platform/openwhisk.js
  knative-build/runtimes/javascript/platform/platform.js
  knative-build/runtimes/javascript/src/service.js
  knative-build/runtimes/javascript/tests/helloworldwithparams/payload-knative-init.http
  knative-build/runtimes/javascript/tests/helloworldwithparams/payload-knative-run.http
Labels: enhancement, review

#235 adding support for binary response (specifically images)
  knative-build/runtimes/javascript/buildtemplate.yaml
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/tests/webactionoptions/data-init-run.json
  knative-build/runtimes/javascript/tests/webactionoptions/payload-knative-init-run.http
Labels: review

#237 Distinguish between dedicated versus stem cell runtimes
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/platform/platform.js
  knative-build/runtimes/javascript/src/service.js
Labels: wip

#238 Enable knative stem runtime for separate init and activation data inv…
  knative-build/runtimes/javascript/platform/knative.js
Labels: enhancement, wip

#241 Add ASF license to gradle files that broke Travis build
  java-local/build.gradle
  java-local/settings.gradle
Labels: build

#242 Seed java runtime source/build files for Knative enablement
  knative-build/runtimes/java/build.gradle
  knative-build/runtimes/java/buildtemplate.yaml
  knative-build/runtimes/java/core/java8/CHANGELOG.md
  knative-build/runtimes/java/core/java8/Dockerfile
  knative-build/runtimes/java/core/java8/build.gradle
  knative-build/runtimes/java/core/java8/delete-build-run.sh
  knative-build/runtimes/java/core/java8/proxy/build.gradle
  knative-build/runtimes/java/core/java8/proxy/compileClassCache.sh
  knative-build/runtimes/java/core/java8/proxy/gradle/wrapper/gradle-wrapper.jar
  knative-build/runtimes/java/core/java8/proxy/gradle/wrapper/gradle-wrapper.properties
  knative-build/runtimes/java/core/java8/proxy/gradlew
  knative-build/runtimes/java/core/java8/proxy/gradlew.bat
  knative-build/runtimes/java/core/java8/proxy/src/main/java/org/apache/openwhisk/runtime/java/action/JarLoader.java
  knative-build/runtimes/java/core/java8/proxy/src/main/java/org/apache/openwhisk/runtime/java/action/Proxy.java
  knative-build/runtimes/java/core/java8/proxy/src/main/java/org/apache/openwhisk/runtime/java/action/WhiskSecurityManager.java
  knative-build/runtimes/java/gradle/README.md
  knative-build/runtimes/java/gradle/docker.gradle
  knative-build/runtimes/java/gradle/wrapper/gradle-wrapper.jar
  knative-build/runtimes/java/gradle/wrapper/gradle-wrapper.properties
  knative-build/runtimes/java/gradlew
  knative-build/runtimes/java/gradlew.bat
  knative-build/runtimes/java/settings.gradle
Labels: knative, wip

#245 Make knative init/run logic more granular/efficient based upon type of request
  knative-build/runtimes/javascript/platform/knative.js
Labels: enhancement

#248 Make knative init/run logic more efficient based upon type of request (body) data
  knative-build/runtimes/javascript/app.js
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/tests/webactionraw/knative-data-init-run.json
  knative-build/runtimes/javascript/tests/webactionraw/knative-data-init.json
  knative-build/runtimes/javascript/tests/webactionraw/knative-data-run.json
  knative-build/runtimes/javascript/tests/webactionraw/openwhisk-data-init.json
  knative-build/runtimes/javascript/tests/webactionraw/openwhisk-data-run.json
  knative-build/runtimes/javascript/tests/webactionraw/payload-knative-init.http
  knative-build/runtimes/javascript/tests/webactionraw/payload-knative-run.http
Labels: enhancement

#249 updates based on Rodric's comments
  knative-build/runtimes/javascript/src/service.js
Labels: review

#251 format changes and adding back initialized as its used by knative
  knative-build/runtimes/javascript/app.js
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/platform/openwhisk.js
  knative-build/runtimes/javascript/src/service.js
Labels: review

#252 Read code from a remote file
  knative-build/runtimes/javascript/buildtemplate.yaml
Labels: knative, review

#253 Fix Knative dedicated function request pre-processing logic
  knative-build/README.md
  knative-build/runtimes/javascript/README.md
  knative-build/runtimes/javascript/platform/knative.js
  knative-build/runtimes/javascript/tests/helloworld/payload-knative-init.http
  knative-build/runtimes/javascript/tests/helloworld/payload-knative-run.http
  knative-build/runtimes/javascript/tests/helloworldwithparams/payload-knative-init-run.http
Labels: bug, documentation, review

#254 fixing function signature which was causing failure
  knative-build/runtimes/javascript/platform/knative.js
Labels: review
