Repository apache/openwhisk-devtools, pull requests merged in 2019-03, with the labels that each got.

#205 Update repo. files to pass scancode tests/fix Travis
  .travis.yml
  CONTRIBUTING.md
  README.md
  docker-compose/.travis/build.sh
  docker-compose/.travis/setup.sh
  docker-compose/README.md
  docker-compose/apigateway/env.conf/api-gateway-env-vars.server.conf
  docker-compose/apigateway/env.conf/api-gateway-env.http.conf
  docker-compose/apigateway/env.conf/api-gateway-upstreams.http.conf
  docker-compose/apigateway/generated-conf.d/whisk-docker-compose.conf
  docker-compose/apigateway/rclone/rclone.conf
  docker-compose/docker-compose.packages.yml
  docker-compose/docker-compose.yml
  java-action-archetype/.travis/build.sh
  java-action-archetype/.travis/setup.sh
  java-action-archetype/README.md
  java-action-archetype/src/test/resources/projects/basic/archetype.properties
  java-local/README.md
  java-local/gradle/wrapper/gradle-wrapper.properties
  java-local/src/main/java/openwhisk/java/local/JavaCompilerLoader.java
  java-local/src/test/resources/aproject/App.java
  maven-java/.mvn/wrapper/maven-wrapper.properties
  maven-java/README.md
  node-local/README.md
  node-local/runtest.sh
  terraform-wskdeploy-plugin/README.md
  terraform-wskdeploy-plugin/main.go
  terraform-wskdeploy-plugin/provider.go
  terraform-wskdeploy-plugin/resource_server.go
  tools/travis/scancode.sh
  tools/travis/setupscan.sh
Labels: bug, build, docker-compose

#207 Removing outdated samples from knative build subdir.
  knative-build/samples/helloworld-nodejs/Dockerfile
  knative-build/samples/helloworld-nodejs/Readme.md
  knative-build/samples/helloworld-nodejs/service.yaml
  knative-build/samples/nodejs-runtime/Readme.md
  knative-build/samples/nodejs-runtime/service.yaml
Labels: documentation

#209 Fix typos and other misc. cleanup
  knative-build/README.md
Labels: documentation

#222 updating dir structure in Dockerfile
  knative-build/runtimes/javascript/Dockerfile
Labels: review

#226 making params (code and action name) optional
  knative-build/runtimes/javascript/README.md
  knative-build/runtimes/javascript/buildtemplate.yaml
Labels: review

#227 sending http metadata as action arguments
  knative-build/runtimes/javascript/platform/platform.js
Labels: review

#230 Fixing typo (copy/paste error) and adding raw test case
  knative-build/runtimes/javascript/platform/platform.js
  knative-build/runtimes/javascript/tests/webactionraw/README.md
  knative-build/runtimes/javascript/tests/webactionraw/build.yaml.tmpl
  knative-build/runtimes/javascript/tests/webactionraw/data-init-run.json
  knative-build/runtimes/javascript/tests/webactionraw/data-init.json
  knative-build/runtimes/javascript/tests/webactionraw/data-run.json
  knative-build/runtimes/javascript/tests/webactionraw/payload-knative-init-run.http
  knative-build/runtimes/javascript/tests/webactionraw/payload-openwhisk-init.http
  knative-build/runtimes/javascript/tests/webactionraw/payload-openwhisk-run.http
  knative-build/runtimes/javascript/tests/webactionraw/service.yaml.tmpl
Labels: review

#231 removing reference to IBM from License file
  LICENSE.txt
Labels: review
